### PR TITLE
add all aws-sdk dependencies

### PR DESCRIPTION
**Pull request by dmurray-chef**
Add all aws-sdk dependencies

## Description
Add all aws-sdk dependencies instead of adding them individually. This will avoid issues when inspec-aws is updated with new resources.

## Related Issue
https://chefio.atlassian.net/browse/TRI-858

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by miah** [comment]
We might do this but need to discuss with infra team. I'm going to close for now.

**Comment by clintoncwolfe** [comment]
The major concern with merging this, as I understand it, is the size of the installation files. In my **personal** opinion, I would lean toward the include-everything approach, at least until we are gaurenteed solid weekly inspec releases (or inspec releases whenever train-aws releases)

I've re-opened and marked do-not-merge, which is more typical for a PR under active review. I had started work on a similar fix and just stumbled on this PR :-)

**Comment by zenspider** [comment]
I'm gonna merge this as we got bit by it again... needs cleanup to happen tho.

**Comment by zenspider** [comment]
Nope. I've been told to hold off on this as it adds ~185 gems to the mix... 60mb and ~2300 files. It'll most likely be untenably slow on the windows side of things.

**Comment by miah** [comment]
Going to re-close this for now. Based on internal discussion about our plans for the year we're going to keep adding individual dependencies until we are able to resolve issues in knife, etc that make adding the 'kitchen sink' problematic.

**Pull request closed without merging**
